services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Matys333\LogHelperBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Utils/'
      - '../tests'